//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpscManagement.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmmoType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AmmoType()
        {
            this.BulletsStocks = new HashSet<BulletsStock>();
            this.WarehouseBulletsStocks = new HashSet<WarehouseBulletsStock>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Identity { get; set; }
        public string Name { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulletsStock> BulletsStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseBulletsStock> WarehouseBulletsStocks { get; set; }
    }
}
