//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpscManagement.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IpscManagementEntities : DbContext
    {
        public IpscManagementEntities()
            : base("name=IpscManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BulletsStock> BulletsStocks { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<BulletsStockHistory> BulletsStockHistories { get; set; }
        public virtual DbSet<AmmoType> AmmoTypes { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<WarehouseBulletsStock> WarehouseBulletsStocks { get; set; }
        public virtual DbSet<WarehouseBulletsStockHistory> WarehouseBulletsStockHistories { get; set; }
    }
}
